<?php


namespace Tests;


use Illuminate\Foundation\Testing\DatabaseMigrations;

class ControllerTestCase extends TestCase
{

    /**
     * Set up
     */
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }


    /**
     * Get auth user
     * @return string|null
     */
    public function getAuthUser()
    {
        $user = $this->json('post','/api/v1/login',[
            'email'=>'admin@admin.com',
            'password'=>'password'
        ]);
        $response = json_decode($user->getContent(),true);

        return $response['token']??null;
    }
}