<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class UrlShortenRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $expression = setting('url_black_list_pattern');
        $pattern = $expression?['not_regex:'.$expression]:[];
        return [
            'long_url'=>array_merge(['required','string','active_url','url'],$pattern),
        ];
    }

    public function messages()
    {
        return [
            'long_url.not_regex'=>'This type of url is blacklisted.'
        ];
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
