<?php


namespace App\Models;


use App\Services\Math;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class Link extends Model
{
    use SoftDeletes;

    protected $fillable = ['short_url','long_url','clicks','expire_at','is_expired'];

    public static function boot()
    {
        static::created(function($model){
            $model->short_url = Math::to_base(1000+$model->id);
            $model->save();

        });
        parent::boot(); // TODO: Change the autogenerated stub
    }

}